version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Yarn Version
          command: yarn --version

      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile

      - run:
          name: Run Tests
          command: yarn test --maxWorkers=2

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Code Coverage
          command: |
            yarn test --maxWorkers=2 --coverage
            bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
